version: "3.9"

services:
  web:
    build:
      context: .
#      target: "runner-test"   # We specify which stage of the dockerfile to use
    env_file:
      - .env
    volumes:
      - ./:/opt/app
    ports: # only if endpoint in dockerfile
      - "8501:8501"
